[tool.poetry]
name = "stress-test"
version = "0.1.0"
description = ""
authors = ["boki <lsb530@naver.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
locust = "^2.20.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

